# Bluetooth
CONFIG_BT_MAX_CONN=5
CONFIG_BT_MAX_PAIRED=5

# Battery
CONFIG_ZMK_BATTERY_REPORTING=y
CONFIG_ZMK_BATTERY_REPORT_INTERVAL=180
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y

# Power management
CONFIG_ZMK_IDLE_TIMEOUT=30000
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=1800000

# ZMK Studio (live keymap-redigering via USB)
CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCK_IDLE_TIMEOUT_SEC=300

# System (navn må maks. være 16 tegn)
CONFIG_ZMK_KEYBOARD_NAME="Ferris Sweep"
